---
- name: deply VM into RHEV
  connection: local
  hosts: localhost

  vars_files:
    - vars/list.yml
    - vars/pass.yml

  tasks:
    - name: Obtain SSO token with username/password
      ovirt_auth:
        url: https://engine.fortnebula.com/ovirt-engine/api
        username: "{{ rhev }}"
        password: "{{ pass }}"

    - name: Deploy VM
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: present
        cluster: Default
        name: "{{ item }}"
        template: rhel-7-base-template
        type: server
        clone: yes
        wait: yes
        cloud_init:
          user_name: "{{ rheluser }}"
          root_password: "{{ rhelpass }}"
          authorized_ssh_keys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf2Ge5kHO1mus3Rrg+4vX9QE++9ilJOuw3iVNDl+/NjiOv1YVBAW882Pl8KHprUWBBLmnCcihV1+r7b+ceadKFPJOYRL21E3bsp5gtEEFA3Jf/GFWkl8WY+sjZ7JpuQuaZsymoUFyu33w11tHDHkhwkOgEhHHuWleUfmLpsQOgevlpC00MkA53I8PSedDFMMiuFaHxIyr9McN0Zr+fdUjzpzhAO7v7Byx9Ete4rhO6PiLQdDSRqvP7BJy9xIkUR82Qeayq4FhghWbFuy8JGlbrHD3eMSat9XdOgvOXq5ZUyG/cRRdQvu8MvqJLZVasDs91hquETqZ+RqiHTBLA9KvL gdykeman@localhost.localdomain'
      with_items: "{{ vms }}"
#      register: output

    - pause:
         minutes: 2

    - ovirt_nics_facts:
        auth: "{{ ovirt_auth }}"
        vm: "{{ item }}"
        name: eth0
      with_items: "{{ vms }}"
      register: nic

    - name: add hosts to in memory inventory
      add_host:
        name: "{{ item.item }}"
        ansible_host: "{{ ovirt_nics[0].reported_devices[0].ips[0].address}}"
        groups: new_hosts
        ansible_ssh_user: root
        ansible_ssh_pass: ansible
      with_items: "{{ nic.results }}"


- include: sub_and_packages.yml
- include: stig.yml
- include: ./examples/apache-basic-playbook/site.yml
