---
- name: Subscription Manager & Initial Packages
  hosts: new_hosts
  become: yes

  vars_files:
    - vars/pass.yml
    - vars/rpms.yml

  tasks:
    - name: register subscription
      redhat_subscription:
        state: present
        username: "{{ uname }}"
        password: "{{ pass }}"
#        force_register: yes
      ignore_errors: yes

    - pause:
        seconds: 10

    - name: attach pool
      command: subscription-manager attach --pool="{{ poolid }}"
      ignore_errors: yes

    - name: add subscription repos
      command: subscription-manager repos --enable "{{ item }}"
      with_items: "{{ rpms }}"

    - name: add rpm
      command: rpm -iUvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      ignore_errors: yes

#    - name: update yum

    - name: Install rhevm-guest-agent
      yum:
        name: rhevm-guest-agent-common
        state: present

    - name: start the service
      service:
        name: ovirt-guest-agent.service
        state: started

    - name: enable service
      service:
        name: ovirt-guest-agent.service
        enabled: yes

    - name: install spice
      yum:
        name: spice-vdagent
        state: present

    - name: start service
      service:
        name: spice-vdagentd
        state: started

    - name: enable service
      service:
        name: spice-vdagentd
        enabled: yes

    - name: yum complete transaction
      command: yum-complete-transaction
      ignore_errors: yes
