---
- name: deply VM into RHEV
  connection: local
  hosts: localhost

  vars_files:
    - vars/list.yml
    - vars/vault.yml

  tasks:
    - name: Obtain SSO token with username/password
      ovirt_auth:
        url: "{{ api }}"
        username: "{{ rhevuser }}"
        password: "{{ rhevpass }}"

    - name: Teardown VM(s)
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: absent
        cluster: Default
        name: "{{ item }}"
      with_items: "{{ vms }}"
      register: output
